language: node_js
sudo: false
before_script:
- git config --global user.email "${git_email}"
- git config --global user.name "${git_name}"
- git checkout master
- git remote add scss https://github.com/TryKickoff/kickoff-scss-test.git
- git fetch scss
- git merge -s ours --no-commit scss/master
- git read-tree --prefix=./assets/src -u scss/master
- git commit -a -m "Imported scss as a subtree. Committed by Travis-CI [ci skip]"
- git push https://${GH_TOKEN}@github.com/TryKickoff/kickoff-scss-test.git master
env:
  global:
    secure: bwPbBdX/+hEdVUpsrp7yg+CGrAx3kkkhUa5EDxNW/hcVBDgGBnPWuqE7E+gNgjeMOPHtx8V67NKXQHL7KGAgfQerZXA3OlXK5O7qK0deN+U1yqf0HBv/8cZHBtgyHXKM+CitdPUdFwvVAfqozenX3vZJ7iEBgLSvaSO+EHdGow+b1T/2hFiwH7uVu2SWZH4ea6jdOvck5JhDqLa20QBYp2riuH/vYEmTok3WMY9aBkgmU959YPAdvXsV2zvLs8Ls00Qx/GWKnzIhThfjJ4tul5wEkDvrclQ6vQCulZLnsefKbMzIyTemKV7HnMhIrc80l7kocbtSgF/CjrIe+/ZsvTSJNaCq5KXTvyRnQwRjOz9fgl0DlXvbdywhjLTwTC2sDNBa5hREz3ztI8B3zglzNvrfR3rLI3nlNvZgujUPECezHyDZ7lHy63lXO1+BpjsN29S2kzQYkKn91ENyn957AdkfU0BpeIAKTIvv/gWKPAfhXAEyRLHQ5sGoVjN7IawJGhrZ1r75ony1qUn452/0zR9HwYqyPtQDI39yyqs55BQ1vX5+OBlfeLRTHu5XrgWMVozPGSWYhTfK9/nfeKl4pyLmdvajTckWNaNvAjQX3/R1zftxeIBkAaPpNt3OexiEZGWzBylf3E+vmGrfk7Vs1D94CsWGbryR3OZOUs6mA+k=
